http:
  port: 8080
# admin:
#   port: 9876
#   host: localhost
apiEndpoints:
  api:
    host: localhost
    methods: GET
    paths: '/user'
  protected:
    host: localhost
    methods: POST
    paths: '/protected'  
serviceEndpoints:
  httpbin:
    url: 'http://localhost:4000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
  - request-transformer
pipelines:
  default:
    apiEndpoints:
      - api
      - protected
    policies:
      - log: # policy name
          - action:    # array of condition/actions objects
              message: ${req.method} ${req.originalUrl} # parameter for log action

    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - jwt:
          - action:
              secretOrPublicKey: 'your_secret_key'
              checkCredentialExistence: false
      - request-transformer:
            action:
              body:
                add:
                  user: req.user
              headers:
                add:
                  user_name: req.user.name
                  user_iat: req.user.iat
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
    
 