http:
  port: 8080
apiEndpoints:
  api:
    host: localhost
    methods: GET
    paths: /user
  protected:
    host: localhost
    methods: POST
    paths: /protected
serviceEndpoints:
  httpbin:
    url: http://localhost:9090
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
  - request-transformer
pipelines:
  default:
    apiEndpoints:
      - api
      - protected
    policies:
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - jwt:
          - action:
              secretOrPublicKey: your_secret_key
              checkCredentialExistence: false
      - request-transformer:
          action:
            body:
              add:
                user: req.user
            headers:
              add:
                user_name: req.user.name
                user_iat: req.user.iat
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
